Create show page
maxwelldevoe/groupProject1 pull request #12
Opened 2018-01-25 16:27 UTC by arpepper139

We created our API endpoint for our show page, edited our FloofShowContainer to fetch from our endpoint, created a FloofShowTile to show the floof data, wrote the necessary tests (which were passing) and renamed our previous FloofTile component to FloofIndexTile to better distinguish between our Tiles.

2018-01-25 20:20 UTC, dpickett requested changes
I left some commentary and also spoke with part of your team about relying on the database for your categories

2018-01-25 20:20 UTC, dpickett commented on app/javascript/containers/FloofShowContainer.js
> +    fetch(`/api/v1/floofs/${id}.json`)
well done

2018-01-25 20:29 UTC, arpepper139 commented
Commenting for self/team: We need to (1) create a "Categories" table, (2) and leverage that categories table to sort our floofs by category. We'll need to revisit our ER diagram for this. 

Also, we should give a unique ID to each array of categories we create per Brianna's comments.

2018-01-26 18:54 UTC, arpepper139 commented
We (1) created the categories table (2) leverages the categories table and serialization to return our Floofs by category, (3) refactored our React environment to utilize our new API data structures (for both the show and index page), and (4) refactored tests to account for changes. All tests were passing at commit.

2018-01-26 19:51 UTC, bkincart requested changes

2018-01-26 19:51 UTC, bkincart commented on app/serializers/category_serializer.rb
> +  def associated_floofs
You can actually just do this with:
```
has_many :floofs
```

2018-01-26 19:51 UTC, bkincart commented on app/serializers/floof_serializer.rb
> +  end
Do you still need to serve up the category name this way? Are you using it somewhere? If not, I'd suggest removing this!

2018-01-26 19:51 UTC, bkincart commented on db/migrate/20180126143956_change_floofs_category_column.rb
> +end
Beautiful migration

2018-01-26 20:22 UTC, bkincart commented on app/javascript/containers/FloofIndexContainer.js
> +        if (category.floofs[0]) {
I would almost prefer something a little more explicit here, such as `if(category.floofs !== [])`

2018-01-26 20:22 UTC, merged